### ISSUE TITLE
What remains on C2SM-wiki after 18. Nov?

### ISSUE THREAD

**Issue by jonasjucker** [C2SM/c2sm.github.io#89]
The status of the following Webs has to be clarified

#### CH-2018
Barely used, could simply be archived, check with @cschnadt 

#### WEW-ICON
Move to MCH-confluence, check with @cschnadt 

#### scClim
A github.io page is a solution, @jonasjucker checks with @leonie-villiger 

#### Extremes
Old page, little content, check with @cschnadt 

Other Webs are checked by @beyerle

**Comment by jonasjucker** [comment]
c2sm-wiki is history

**Comment by beyerle** [comment]
Old c2sm wiki content can maybe still be found here: https://wiki.wcr.ethz.ch/Main/OldPages
